### ISSUE TITLE
ModuleNotFoundError: No module named 'dask.graph_manipulation'

### ISSUE THREAD

**Issue by RishabhKlaim** [coiled/dask-mongo#17]
Unable to read dask_mongo

**Comment by phobson** [comment]
Thanks for the reporting this issue @RishabhKlaim. Could you provide a little more context? 

Which version of dask are you using? Does this happen when you import `dask_mongo` or when you try to interact with your database?

**Comment by RishabhKlaim** [comment]
Thanks for the prompt reply.
Yes, It happens when I import dask_mongo.
I have installed dask-mongo using pip and also tried it usin conda but the error persists .

![56518E7B-6AAC-4539-9ED9-5EBAA7FE32D2_4_5005_c](https://user-images.githubusercontent.com/95687647/169337708-fc174e52-d761-43e6-8241-a13a1e8ac135.jpeg)

**Comment by phobson** [comment]
Which version of dask are you using?

**Comment by RishabhKlaim** [comment]
'2.30.0'

**Comment by phobson** [comment]
That's a very old version of dask.

Could you try your notebook again after updating it?
```zsh
conda update dask
```

**Comment by RishabhKlaim** [comment]
`Conda update dask` not working. 

Updating dask is constricted by 

anaconda -> requires dask==2.30.0=py_0
O/P
**If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`**

Can you let me know the exact version so I can try conda install dask.<version>

**Comment by phobson** [comment]
The current version of dask is 2022.5.0.

I recommend you either update all of the packages like the message suggests or create a new conda environment for this:

```zsh
conda create --name=dask-env python=3.9 dask dask-mongo --channel=conda-forge
```

In the command above, be sure to include any additional dependencies you might need in your environment. Follow conda's prompts to finish creating the environment. And finally try it out with something like:

```zsh
conda activate dask-env
(dask-env) python -c "import dask_mongo"
```

**Comment by phobson** [comment]
Just confirmed that this is working with the current version of dask:

```
15:25:39 in ~ via 🅒 base took 6s
➜ mamba create --name=mongo python=3.9 dask-mongo

15:26:10 in ~ via 🅒 base took 17s
➜ mamba activate mongo

15:26:22 in ~ via 🅒 mongo
➜ python -c "import dask_mongo; print(dask_mongo.__version__)"
2021.7.3
```

**Comment by RishabhKlaim** [comment]
Perfect. Sounds good. Vend worked. Thanks for the assistance
