### ISSUE TITLE
Replace name of `read_partition` to include mongo

### ISSUE THREAD

**Issue by ncclementi** [coiled/dask-mongo#4]
When reading from mongo  using `read_mongo` the low low-level functions that shows up on the task-stream plot in the dashboard is `read_partitions` . We want this to make a reference that is reading from a mongo database, therefore we should change the name. 

One option could be `fetch_mongo_partitions`, but it seems long. Any suggestions?

**Comment by jrbourbeau** [comment]
Closed via https://github.com/coiled/dask-mongo/pull/2. Thanks @ncclementi
